# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b06ca0392c8c2613f4d1249974ef37653333500a61da0ec717515fd0e9e7309771c43e2702aa1afb2cd67578073914475e981ac25e05ac9d9507d5359b1de2a

test:
  secret_key_base: 3cb65511dfbfcf5698c6e8d3db1e0f025cf4f0070abcfea495456f412dc2c80a2a8a1db22483a8c0885504610337985c8a17e0de23b3c2e0a34d17e95a055016

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
